language: java
node_js: 10

install:
  - wget http://us.mirrors.quenda.co/apache/rocketmq/4.3.2/rocketmq-all-4.3.2-bin-release.zip
  - unzip rocketmq-all-4.3.2-bin-release.zip
  - cd rocketmq-all-4.3.2-bin-release
  - perl -i -pe's/-Xms8g -Xmx8g -Xmn4g/-Xms2g -Xmx2g -Xmn1g/g' bin/runbroker.sh
  - nohup sh bin/mqnamesrv &
  - nohup sh bin/mqbroker -n localhost:9876 &
  - sleep 10
  - ./bin/mqadmin updateTopic -b '127.0.0.1:10911' –n '127.0.0.1:9876' -t test
  - ./bin/mqadmin updateSubGroup -b '127.0.0.1:10911' –n '127.0.0.1:9876' -g testGroup

script:
  - npm test

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
      before_install:
        - jdk_switcher use oraclejdk8
    - os: windows
    - os: osx
      osx_image: xcode9.3
      env:
        JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre
